// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVgsluF2Do11azBrHqRQyrNdojAUXy97Y',
    appId: '1:1082815366088:web:bd36e5b6e5a0330c82f6fd',
    messagingSenderId: '1082815366088',
    projectId: 'speedyship-ec358',
    authDomain: 'speedyship-ec358.firebaseapp.com',
    storageBucket: 'speedyship-ec358.appspot.com',
    measurementId: 'G-WFJ8XYEJRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbfY4VSOzUlvDaGyglZw8-_u0kqv2zWAI',
    appId: '1:1082815366088:android:8b8005c1d4f329d682f6fd',
    messagingSenderId: '1082815366088',
    projectId: 'speedyship-ec358',
    storageBucket: 'speedyship-ec358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY6_up_pWvMTjJfeEYBgeWX443tzhm2fM',
    appId: '1:1082815366088:ios:323caff3b0be86b782f6fd',
    messagingSenderId: '1082815366088',
    projectId: 'speedyship-ec358',
    storageBucket: 'speedyship-ec358.appspot.com',
    iosClientId:
        '1082815366088-0i4khe73deg3gkm9fhe2jtas57p3re1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedyship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY6_up_pWvMTjJfeEYBgeWX443tzhm2fM',
    appId: '1:1082815366088:ios:323caff3b0be86b782f6fd',
    messagingSenderId: '1082815366088',
    projectId: 'speedyship-ec358',
    storageBucket: 'speedyship-ec358.appspot.com',
    iosClientId:
        '1082815366088-0i4khe73deg3gkm9fhe2jtas57p3re1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.speedyship',
  );
}
